// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImageInfrastructure.Core.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20210518005714_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2");

            modelBuilder.Entity("ImageImageTag", b =>
                {
                    b.Property<int>("ImagesImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsImageTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImagesImageId", "TagsImageTagId");

                    b.HasIndex("TagsImageTagId");

                    b.ToTable("ImageImageTag");
                });

            modelBuilder.Entity("ImageInfrastructure.Core.Models.ArtistAccount", b =>
                {
                    b.Property<int>("ArtistAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("ArtistAccountId");

                    b.HasIndex("ImageId");

                    b.ToTable("ArtistAccounts");
                });

            modelBuilder.Entity("ImageInfrastructure.Core.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Blob")
                        .HasColumnType("BLOB");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ImageInfrastructure.Core.Models.ImageSource", b =>
                {
                    b.Property<int>("ImageSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.HasKey("ImageSourceId");

                    b.HasIndex("ImageId");

                    b.ToTable("ImageSources");
                });

            modelBuilder.Entity("ImageInfrastructure.Core.Models.ImageTag", b =>
                {
                    b.Property<int>("ImageTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Safety")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageTagId");

                    b.ToTable("ImageTags");
                });

            modelBuilder.Entity("ImageImageTag", b =>
                {
                    b.HasOne("ImageInfrastructure.Core.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImageInfrastructure.Core.Models.ImageTag", null)
                        .WithMany()
                        .HasForeignKey("TagsImageTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImageInfrastructure.Core.Models.ArtistAccount", b =>
                {
                    b.HasOne("ImageInfrastructure.Core.Models.Image", null)
                        .WithMany("ArtistAccounts")
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("ImageInfrastructure.Core.Models.ImageSource", b =>
                {
                    b.HasOne("ImageInfrastructure.Core.Models.Image", "Image")
                        .WithMany("Sources")
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ImageInfrastructure.Core.Models.Image", b =>
                {
                    b.Navigation("ArtistAccounts");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
