// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ImageInfrastructure.Core.CompiledModels
{
    partial class CoreContextModel
    {
        partial void Initialize()
        {
            var artistAccountImage = ArtistAccountImageEntityType.Create(this);
            var imageImageTag = ImageImageTagEntityType.Create(this);
            var artistAccount = ArtistAccountEntityType.Create(this);
            var image = ImageEntityType.Create(this);
            var imageBlob = ImageBlobEntityType.Create(this);
            var imageSource = ImageSourceEntityType.Create(this);
            var imageTag = ImageTagEntityType.Create(this);
            var relatedImage = RelatedImageEntityType.Create(this);
            var responseCache = ResponseCacheEntityType.Create(this);

            ArtistAccountImageEntityType.CreateForeignKey1(artistAccountImage, artistAccount);
            ArtistAccountImageEntityType.CreateForeignKey2(artistAccountImage, image);
            ImageImageTagEntityType.CreateForeignKey1(imageImageTag, image);
            ImageImageTagEntityType.CreateForeignKey2(imageImageTag, imageTag);
            ImageBlobEntityType.CreateForeignKey1(imageBlob, image);
            ImageSourceEntityType.CreateForeignKey1(imageSource, image);
            RelatedImageEntityType.CreateForeignKey1(relatedImage, image);
            RelatedImageEntityType.CreateForeignKey2(relatedImage, imageSource);

            ArtistAccountEntityType.CreateSkipNavigation1(artistAccount, image, artistAccountImage);
            ImageEntityType.CreateSkipNavigation1(image, artistAccount, artistAccountImage);
            ImageEntityType.CreateSkipNavigation2(image, imageTag, imageImageTag);
            ImageTagEntityType.CreateSkipNavigation1(imageTag, image, imageImageTag);

            ArtistAccountImageEntityType.CreateAnnotations(artistAccountImage);
            ImageImageTagEntityType.CreateAnnotations(imageImageTag);
            ArtistAccountEntityType.CreateAnnotations(artistAccount);
            ImageEntityType.CreateAnnotations(image);
            ImageBlobEntityType.CreateAnnotations(imageBlob);
            ImageSourceEntityType.CreateAnnotations(imageSource);
            ImageTagEntityType.CreateAnnotations(imageTag);
            RelatedImageEntityType.CreateAnnotations(relatedImage);
            ResponseCacheEntityType.CreateAnnotations(responseCache);

            AddAnnotation("ProductVersion", "6.0.0-preview.6.21352.1");
        }
    }
}
